bed_file: "Panel.bed"

filter_thresholds:
  DP: 100   # Depth Coverage
  GQ: 99    # Genotype Quality

#######################
known_sites: "Mills_and_1000G_gold_standard.indels.b37.vcf"
ref: "GRCh37.p13.genome.fa"
bowtie_index: "GRCh37"
docker_data: "/VEP_data"